[workspace]
authors = ["sasaki_mac <0704waffle@gmail.com>"]
channels = ["conda-forge"]
name = "PaperBot"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
google-generativeai = ">=0.8.6,<0.9"
requests = ">=2.32.5,<3"
arxiv = ">=2.4.0,<3"
habanero = ">=2.3.0,<3"
google-auth = ">=2.48.0,<3"
google-auth-oauthlib = ">=1.2.2,<2"
google-auth-httplib2 = ">=0.3.0,<0.4"
google-api-python-client = ">=2.196.0,<3"
google-genai = ">=1.68.0,<3"
